language: python
python:
  - "3.6"

services:
  - docker

notifications:
  slack: edserlabs:KKbi0flnhS1wMA6MzONdm2G0

before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"
