language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
  
scripts:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"
